<<<<<<< HEAD
<<<<<<< HEAD
bazel test --config tflite //band/...
=======
bazel test -c dbg --define tflite=true //band/...
>>>>>>> 3baeae2e... Offline save / log + fname-based model matching
=======
bazel test --define tflite=true //band/...
>>>>>>> 37878a67... undo change on sh
