# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/common.proto\x12\nband_proto\"\x06\n\x04Void\"\x15\n\x05Shape\x12\x0c\n\x04\x64ims\x18\x02 \x03(\x05\"E\n\x06Status\x12$\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x16.band_proto.StatusCode\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\x13\n\x05OpSet\x12\n\n\x02op\x18\x01 \x03(\x05*\x99\x01\n\x08\x44\x61taType\x12\x0b\n\x07NO_TYPE\x10\x00\x12\x0b\n\x07\x46LOAT32\x10\x01\x12\t\n\x05INT32\x10\x02\x12\t\n\x05UINT8\x10\x03\x12\t\n\x05INT64\x10\x04\x12\n\n\x06STRING\x10\x05\x12\x08\n\x04\x42OOL\x10\x06\x12\t\n\x05INT16\x10\x07\x12\r\n\tCOMPLEX64\x10\x08\x12\x08\n\x04INT8\x10\t\x12\x0b\n\x07\x46LOAT16\x10\n\x12\x0b\n\x07\x46LOAT64\x10\x0b*@\n\x10QuantizationType\x12\x13\n\x0fNO_QUANTIZATION\x10\x00\x12\x17\n\x13\x41\x46\x46INE_QUANTIZATION\x10\x01*=\n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\x11\n\rUNKNOWN_ERROR\x10\x01\x12\x14\n\x10INVALID_ARGUMENT\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATATYPE._serialized_start=158
  _DATATYPE._serialized_end=311
  _QUANTIZATIONTYPE._serialized_start=313
  _QUANTIZATIONTYPE._serialized_end=377
  _STATUSCODE._serialized_start=379
  _STATUSCODE._serialized_end=440
  _VOID._serialized_start=34
  _VOID._serialized_end=40
  _SHAPE._serialized_start=42
  _SHAPE._serialized_end=63
  _STATUS._serialized_start=65
  _STATUS._serialized_end=134
  _OPSET._serialized_start=136
  _OPSET._serialized_end=155
# @@protoc_insertion_point(module_scope)
