# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/model.proto\x12\nband_proto\x1a\x12proto/common.proto\"\x95\x02\n\x0fModelDescriptor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0f\n\x07num_ops\x18\x03 \x01(\x05\x12\x13\n\x0bnum_tensors\x18\x04 \x01(\x05\x12*\n\x0ctensor_types\x18\x05 \x03(\x0e\x32\x14.band_proto.DataType\x12\x1c\n\x14input_tensor_indices\x18\x06 \x03(\x05\x12\x1d\n\x15output_tensor_indices\x18\x07 \x03(\x05\x12+\n\x10op_input_tensors\x18\x08 \x03(\x0b\x32\x11.band_proto.OpSet\x12,\n\x11op_output_tensors\x18\t \x03(\x0b\x32\x11.band_proto.OpSetb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODELDESCRIPTOR._serialized_start=54
  _MODELDESCRIPTOR._serialized_end=331
# @@protoc_insertion_point(module_scope)
