# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import tensor_pb2 as proto_dot_tensor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/request.proto\x12\nband_proto\x1a\x12proto/tensor.proto\">\n\rRequestOption\x12-\n\x0c\x62\x61\x63kend_type\x18\x01 \x01(\x0e\x32\x17.band_proto.BackendType\"Y\n\x07Request\x12)\n\x06option\x18\x01 \x01(\x0b\x32\x19.band_proto.RequestOption\x12#\n\x07tensors\x18\x02 \x03(\x0b\x32\x12.band_proto.Tensor*U\n\x0b\x42\x61\x63kendType\x12\x0e\n\nTENSORFLOW\x10\x00\x12\x0b\n\x07PYTORCH\x10\x01\x12\x0f\n\x0bONNXRUNTIME\x10\x02\x12\x0c\n\x08TENSORRT\x10\x03\x12\n\n\x06\x43USTOM\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.request_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BACKENDTYPE._serialized_start=210
  _BACKENDTYPE._serialized_end=295
  _REQUESTOPTION._serialized_start=55
  _REQUESTOPTION._serialized_end=117
  _REQUEST._serialized_start=119
  _REQUEST._serialized_end=208
# @@protoc_insertion_point(module_scope)
