# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/response.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as proto_dot_common__pb2
from proto import tensor_pb2 as proto_dot_tensor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/response.proto\x12\nband_proto\x1a\x12proto/common.proto\x1a\x12proto/tensor.proto\"S\n\x08Response\x12\"\n\x06status\x18\x01 \x01(\x0b\x32\x12.band_proto.Status\x12#\n\x07tensors\x18\x02 \x03(\x0b\x32\x12.band_proto.Tensor\"\x13\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.response_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE._serialized_start=76
  _RESPONSE._serialized_end=159
  _EVENT._serialized_start=161
  _EVENT._serialized_end=180
# @@protoc_insertion_point(module_scope)
