# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import common_pb2 as proto_dot_common__pb2
from proto import model_pb2 as proto_dot_model__pb2
from proto import request_pb2 as proto_dot_request__pb2
from proto import response_pb2 as proto_dot_response__pb2


class BandServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetModelDesc = channel.unary_stream(
                '/band_proto.BandService/GetModelDesc',
                request_serializer=proto_dot_common__pb2.Void.SerializeToString,
                response_deserializer=proto_dot_model__pb2.ModelDescriptor.FromString,
                )
        self.CheckModelDesc = channel.unary_unary(
                '/band_proto.BandService/CheckModelDesc',
                request_serializer=proto_dot_model__pb2.ModelDescriptor.SerializeToString,
                response_deserializer=proto_dot_common__pb2.Status.FromString,
                )
        self.RequestSync = channel.unary_unary(
                '/band_proto.BandService/RequestSync',
                request_serializer=proto_dot_request__pb2.Request.SerializeToString,
                response_deserializer=proto_dot_response__pb2.Response.FromString,
                )


class BandServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetModelDesc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckModelDesc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BandServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetModelDesc': grpc.unary_stream_rpc_method_handler(
                    servicer.GetModelDesc,
                    request_deserializer=proto_dot_common__pb2.Void.FromString,
                    response_serializer=proto_dot_model__pb2.ModelDescriptor.SerializeToString,
            ),
            'CheckModelDesc': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckModelDesc,
                    request_deserializer=proto_dot_model__pb2.ModelDescriptor.FromString,
                    response_serializer=proto_dot_common__pb2.Status.SerializeToString,
            ),
            'RequestSync': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestSync,
                    request_deserializer=proto_dot_request__pb2.Request.FromString,
                    response_serializer=proto_dot_response__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'band_proto.BandService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BandService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetModelDesc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/band_proto.BandService/GetModelDesc',
            proto_dot_common__pb2.Void.SerializeToString,
            proto_dot_model__pb2.ModelDescriptor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckModelDesc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/band_proto.BandService/CheckModelDesc',
            proto_dot_model__pb2.ModelDescriptor.SerializeToString,
            proto_dot_common__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/band_proto.BandService/RequestSync',
            proto_dot_request__pb2.Request.SerializeToString,
            proto_dot_response__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
