# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as proto_dot_common__pb2
from proto import request_pb2 as proto_dot_request__pb2
from proto import response_pb2 as proto_dot_response__pb2
from proto import model_pb2 as proto_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/service.proto\x12\nband_proto\x1a\x12proto/common.proto\x1a\x13proto/request.proto\x1a\x14proto/response.proto\x1a\x11proto/model.proto2\xd1\x01\n\x0b\x42\x61ndService\x12\x41\n\x0cGetModelDesc\x12\x10.band_proto.Void\x1a\x1b.band_proto.ModelDescriptor\"\x00\x30\x01\x12\x43\n\x0e\x43heckModelDesc\x12\x1b.band_proto.ModelDescriptor\x1a\x12.band_proto.Status\"\x00\x12:\n\x0bRequestSync\x12\x13.band_proto.Request\x1a\x14.band_proto.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BANDSERVICE._serialized_start=118
  _BANDSERVICE._serialized_end=327
# @@protoc_insertion_point(module_scope)
