# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tensor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/tensor.proto\x12\nband_proto\x1a\x12proto/common.proto\"Y\n\x17\x41\x66\x66ineQuantizationParam\x12\r\n\x05scale\x18\x01 \x03(\x02\x12\x12\n\nzero_point\x18\x02 \x03(\x05\x12\x1b\n\x13quantized_dimension\x18\x03 \x01(\x05\"u\n\x0cQuantization\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.band_proto.QuantizationType\x12\x39\n\x0c\x61\x66\x66ine_param\x18\x02 \x01(\x0b\x32#.band_proto.AffineQuantizationParam\"\x9b\x01\n\x06Tensor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x05shape\x18\x02 \x01(\x0b\x32\x11.band_proto.Shape\x12#\n\x05\x64type\x18\x03 \x01(\x0e\x32\x14.band_proto.DataType\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12.\n\x0cquantization\x18\x05 \x01(\x0b\x32\x18.band_proto.Quantizationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.tensor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AFFINEQUANTIZATIONPARAM._serialized_start=54
  _AFFINEQUANTIZATIONPARAM._serialized_end=143
  _QUANTIZATION._serialized_start=145
  _QUANTIZATION._serialized_end=262
  _TENSOR._serialized_start=265
  _TENSOR._serialized_end=420
# @@protoc_insertion_point(module_scope)
