# This token is generated by mrsnu-bot account. The account has read-only access to our repos.
# The token can be deleted whenever we want.
export GITHUBTOKEN=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
export TENSORFLOW_LIB=libtensorflow_framework.so.2
export TENSORFLOW_LIB_PATH=tensorflow/${TENSORFLOW_LIB}

# Download tensorflow v2.3.0 lib from `tests` branch in `mrsnu/tflite` branch.
function get_tensorflow_lib {
  if [ -f "$TENSORFLOW_LIB_PATH" ];then
    echo "Tensorflow library exists."
  else
    curl -s -O https://${GITHUBTOKEN}@raw.githubusercontent.com/mrsnu/tflite/tests/${TENSORFLOW_LIB_PATH} && mv ${TENSORFLOW_LIB} ${TENSORFLOW_LIB_PATH}
  fi
}

# Delete the tensorflow lib if exists.
function delete_tensorflow_lib {
  if [ -f "$TENSORFLOW_LIB_PATH" ];then
    rm ${TENSORFLOW_LIB_PATH}
  else
    echo "Tensorflow library does not exist."
  fi
}
