# load("//band:band.bzl", "band_cc_library")

# package(
#     default_visibility = ["//visibility:public"],
#     licenses = ["notice"],  # Apache 2.0
# )

# band_cc_library(
#     name = "graph",
#     hdrs = [
#         "graph_interface.h",
#         "graph.h",
#         "node.h",
#         "graph_builder.h",
#         "invariant.h",
#     ],
#     srcs = [
#         "graph.cc",
#         "node.cc",
#         "graph_builder.cc",
#         "invariant.cc",
#     ],
#     deps = [
#         "//band:model",
#         "//band:tensor",
#     ]
# )